name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
     stage: build
     only:
      - master
  scripts:
     - npm install
     - npm run build
  artifacts:
     paths:
      - build/
 
deploy:
  stage: deploy
   only:
     - master
     image: python:latest
     dependencies:
       - build
     script:
     - pip install awscli
     - aws s3 cp build/ s3://$S3_BUCKET_NAME/ --recursive --include "*" 
